In [1]:
import numpy as np


1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [2]:
data = np.loadtxt(r'J:\pyfiles\minutes_n_ingredients.csv', delimiter=',', skiprows=1, dtype=np.int32)
data[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [3]:
first_col_сut = data[:, 1:]
max = np.max(first_col_сut, axis=0)
min = np.min(first_col_сut, axis=0)
median = np.median(first_col_сut, axis=0)
mean = np.mean(first_col_сut, axis=0)
print(max)
print(min)
print(median)
print(mean)

[2147483647         39]
[0 1]
[40.  9.]
[2.16010017e+04 9.05528000e+00]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [4]:
q_75 = np.quantile(data[:, 1], 0.75)
data[:, 1] = np.clip(data[:, 1], 0, q_75)
data[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [5]:
print(f"Продолжительность равна нулю для {(data[:, 1] == 0).sum()} рецептов.")
data[:, 1][data[:, 1] == 0] = 1

Продолжительность равна нулю для 479 рецептов.


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [6]:
print(f"В датасете находится {len(np.unique(data[:, 0]))} уникальных рецептов.")

В датасете находится 100000 уникальных рецептов.


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [7]:
unique_ing = np.unique(data[:, 2])
unique_ing_len = len(unique_ing)

print(f"В датасете присутствует {unique_ing_len} различных значений количества ингредиентов:")
print(f"Количество ингредиентов: {unique_ing}")

В датасете присутствует 37 различных значений количества ингредиентов:
Количество ингредиентов: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [8]:
data_up = data[data[:, 2] <= 5]
data_up[:5]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       [484223,     18,      4],
       [ 63150,     65,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [9]:
ing_per_minute = data[:, 2] / data[:, 1]
max_ing_per_minute = np.max(ing_per_minute)
print(f"Среднее количество ингредиентов на одну минуту: {ing_per_minute}")
print(f"Максимальное количество ингредиентов на одну минуту: {max_ing_per_minute}")

Среднее количество ингредиентов на одну минуту: [0.26666667 0.28       0.6        ... 0.23076923 0.8        0.21538462]
Максимальное количество ингредиентов на одну минуту: 24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [10]:
sort_data = data[data[:, 1].argsort()[::-1]]
top_100 = sort_data[:100]
ing_top_100 = np.mean(top_100[:, 2])
ing_top_100

9.96

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [11]:
random_data = np.random.choice(data.shape[0], size=10, replace=False)
random_recipes = data[random_data]
print(random_recipes)

[[110094     50     11]
 [ 54009     65     10]
 [286856     40     13]
 [305537     60      4]
 [  4546     25      5]
 [462526     45     12]
 [264448     65      9]
 [ 66105     35      5]
 [419685     35      9]
 [427586     50     11]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [12]:
print(f"Процент рецептов, количество ингредиентов в которых меньше среднего: {(len(data[data[:, 2] < np.mean(data[:, 2])]) / len(data)) * 100:.2f}%")

Процент рецептов, количество ингредиентов в которых меньше среднего: 58.80%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [13]:
data_easy = np.column_stack((data, np.where((data[:, 1] <= 20) & (data[:, 2] <= 5), 1, 0)))
data_easy

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [14]:
print(f"Процент рецептов, количество ингредиентов в которых меньше среднего: {(np.sum(data_easy[:,3]) / len(data)) * 100:.2f}%")

Процент рецептов, количество ингредиентов в которых меньше среднего: 9.55%


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [15]:
first_col_сut = data[:, 1:]
short_recipes = first_col_сut[first_col_сut[:, 0] < 10]
standard_recipes = first_col_сut[(first_col_сut[:, 0] >= 10) & (first_col_сut[:, 1] < 20)]
long_recipes = first_col_сut[first_col_сut[:, 0] >= 20]
print(len(short_recipes), len(standard_recipes),len(long_recipes))
new_array = np.zeros((3, len(short_recipes), 2), dtype=np.int32)
new_array[0, :len(short_recipes), :] = short_recipes[:len(short_recipes), :]
new_array[1, :len(standard_recipes), :] = standard_recipes[:len(short_recipes), :]
new_array[2, :len(long_recipes), :] = long_recipes[:len(short_recipes), :]
new_array.shape

7588 91349 79751


(3, 7588, 2)